### ISSUE TITLE
ESPHome 2025.7.0 built results in failed config

### ISSUE THREAD

**Issue by mhoogenbosch** [smarthomeshop/ultimatesensor-mini#13]
```
INFO ESPHome 2025.7.0
INFO Reading configuration /config/esphome/ultimatesensor-mini.yaml...
Failed config

light.esp32_rmt_led_strip: [source /data/packages/4983a4d1/ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml:187]
  platform: esp32_rmt_led_strip
  rgb_order: GRB
  pin: GPIO20
  num_leds: 1
  
  [rmt_channel] is an invalid option for [light.esp32_rmt_led_strip]. Please check the indentation.
  rmt_channel: 0
  chipset: ws2812
  name: Back light
  id: rgb_back_light
```
Nothing much else to tell.

**Comment by mhoogenbosch** [comment]
When I disable     rmt_channel: 1 and the 0 with the other light, it starts building. I'll check if it still works.

**Comment by dwainscheeren** [comment]
Fixed by thanks of @Diondk #15

**Comment by Romkabouter** [comment]
Still failing github://smarthomeshop/ultimatesensor-mini/ultimatesensor-mini-v1/ultimatesensor-mini-complete.yaml@main

<img width="1064" height="410" alt="Image" src="https://github.com/user-attachments/assets/d5cf01a6-43db-471b-874d-220f26f25ef1" />
